<<<<<<< HEAD
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019, The Linux Foundation. All rights reserved.

export CONFIG_SPECTRA_CAMERA_KONA=y
export CONFIG_SPECTRA_CAMERA=y
=======
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2019, The Linux Foundation. All rights reserved.


export CONFIG_SPECTRA_CAMERA=y
>>>>>>> 0261548dd41b (techpack: camera: Import changes from RealmeUI 4.0)
